### ISSUE TITLE
Support for a serverless and/or peer-to-peer architecture

### ISSUE THREAD

**Issue by jasdeepkhalsa** [cesanta/smart.js#10]
In one use case of IoT we have a need for a server for remote device management, however, I think this will be a minority usage.

The most usage will be for IoT devices to be as self-contained as possible, without the need to rely on anything outside of itself. Besides, as IoT reaches its peak, servers are going to get hammered and some people/companies may wish to avoid this altogether. It is also more secure if there is less reliance on something external.

There are a few ways to achieve this:

1. Bundle the server with the client. Since this is Node.js, this should not be too difficult. It may increase the size of the storage required but it would be another option to have everything self-contained, including the datastore. In fact, there may not even be a need for this extra server code (similar to https://webtask.io/docs/how).
2. Give each IoT device the ability to talk directly to other devices via P2P technology e.g. Bittorrent. This would also eliminate the need for a central server. IoT devices can fetch bits of data from other devices and maybe each device has a copy of the other devices settings. This way even if one IoT device fails, the data is still secure.

Would be great to get your thoughts on this!

**Comment by cpq** [comment]
Thanks for following up, @jasdeepkhalsa 

Smart.js is already server-less. And, comms protocol is peer-to-peer, see https://cesanta.com/docs/cloud/
And, Smart.js is NOT nodejs-based. We use our own JS engine, which is way smaller then V8.

Regards,
