### ISSUE TITLE
Example "http server example" isn't working

### ISSUE THREAD

**Issue by olterion** [cesanta/smart.js#100]
Hello,

I have a working smart.js firmware on a ESP12-E with 4MB flash.
At the moment I have the Beta2 smart.js firmware on it.
I want to have a little standalone webserver like in the "http webserver example" shown.
But I can't get it running.
I store the code snippets from https://www.cesanta.com/developer/smartjs#_http_server_example at "http_server_1.js" and "index.html" an load it onto the ESP12-E.
The I type `File.eval('http_server_1.js')` into the FNC console and here is the failure:

`Exec error: {"message":"Cannot bind"}`

When I try the functionality of this project, I can see the html page in the webbrowser under the IP address of my board.
But if I enter a GPIO port and push "Set" on the page, nothing happens. The port voltage doesn't change and the page become blank and the address stays at `board_ip/gpio`.
Also in the FNC console nothing receives.

So, what can be wrong in this case?

**Comment by TRAHOMOTO** [comment]
Same problems

**Comment by mmikulicic** [comment]
That's because smartjs boots with a webserver on port 80, please use another port.

Sorry, we'll update the doc and show how to disable the embedded web conf web server.

**Comment by TRAHOMOTO** [comment]
Yes! You are damn right!
