### ISSUE TITLE
GPIO.setisr stuck

### ISSUE THREAD

**Issue by intx82** [cesanta/smart.js#101]
When use GPIO.setisr and pin goes to another state esp module halted and reseted with wdt

```

smartjs 34760/696$ GPIO.setmode(14,3,0);
false
smartjs 35304/792$ GPIO.setmode(14,1,0);
true
smartjs 35240/692$ GPIO.setisr(14,3,function(){print("GOTISR");});
true


```
after this, i changed pin state and esp-12q stuck, and reseted with wdt

PS: Может лучше по-русски?

**Comment by realzeus** [comment]
The same behavior on ESP-01.

**Comment by alashkin** [comment]
Hi!
Try to rebuild smartjs@master, should be fixed.
```
GPIO.setmode(14,3,0);
GPIO.setisr(14,3,function(){print("GOTISR");});
```

`GPIO.setmode(14,3,0);` should return `true`, is as an issue as well.

**Comment by intx82** [comment]
+alashkin
Yes, it's work!   thank you for review this issue.

**Comment by alashkin** [comment]
Cool!
Thank you for reporting issue.
