### ISSUE TITLE
"Save Configuration" does not work silently

### ISSUE THREAD

**Issue by realzeus** [cesanta/smart.js#104]
"Save Configuration" does not work and does not show any error message.
Caused by missing value for http port. It should be 80.

This "conf.json" fixes it: {"http": {"port": 80}}"

Value has to be updated in "conf_sys_defaults.json"

**Comment by mmikulicic** [comment]
thanks for reporting this; actually it's the other way around, `port` was the old name and has been renamed to `listen_addr` but we forgot to update the schema. Fixing
