### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by bartmichu** [cesanta/smart.js#11]
Hi, is it possible to evaluate your interpreter without any extra hardware, i.e. run it on a linux machine?

**Comment by mmikulicic** [comment]
Hi, we're working on a port of the smart.js platform to posix environments. In the meantime if you want to run the bare JS interpreter that lies at the heart of smart.js, check out https://github.com/cesanta/v7 

It can be used either as a C library or as a standalone binary on unices and windows.

**Comment by bartmichu** [comment]
Sounds good, thanks.
