### ISSUE TITLE
cc3200 sys_init.js

### ISSUE THREAD

**Issue by javatai** [cesanta/smart.js#111]
Dear Sir:
   I have flash the smartjs-CC3200-beta3.zip, but I can't use http://192.168.4.1
checked that sys_init.js file is zero size.

Does cc3200 support ap mode now ?

Thanks you
BRs
Anson

**Comment by rojer** [comment]
there was a bug in AP initialization which was fixed in https://github.com/cesanta/smart.js/commit/9df31ea6dd0352343c8dffc9da9a47770baeb2b4
