### ISSUE TITLE
WebDAV does not work

### ISSUE THREAD

**Issue by kroshilin** [cesanta/smart.js#112]
I flashed ESP-01 with Beta3. Everything is ok, but on Windows 10 I can't establish connection using WebDAV. Error is "Wrong folder name".

**Comment by kroshilin** [comment]
However, I can send files to device using curl -T filename.txt http://192.168.1.121/filename.txt

**Comment by 4713** [comment]
WebDAV is also not functioning with davfs2 on Raspberry or tools like carotdav on Windows.
Both tools seem to mount the device but read/write is not possible.

**Comment by cpq** [comment]
cc @alashkin 

After spending much time fixing WebDAV, we decided to discontinue WebDAV feature.
Using WebDAV would be great, but making it work takes a LOT of effort.
We will resort to HTTP POST(curl), and also we're working on the online editor that will make things easy.

@alashkin , please remove WebDAV from the documentation, and from the source code, and close this bug.

**Comment by alashkin** [comment]
Removed in https://github.com/cesanta/smart.js/commit/5d2953a6f412bd9663fec8ce0fbcfd46b7715583
