### ISSUE TITLE
continuous reboot

### ISSUE THREAD

**Issue by carterw** [cesanta/smart.js#118]
I decided to try out the most recent commits so I went through the procedure for extracting and building the firmware, and was able to flash it with no problem.

The first thing I did after that was;
Wifi.setup("yourssid", "youpassword")

The device joined my network and all seemed well. Unfortunately, after a reset the device reboots over and over.

**Comment by alashkin** [comment]
@carterw 

Hi, I cannot reproduce this, so, I need any details.
First of all, what esp model do you use? What size of its flash?

**Comment by carterw** [comment]
According to the case markings it is a;
ESP-12
ESP8266MOD

**Comment by alashkin** [comment]
I.e. it has 4MB flash?
Strange.
Ok, could you past here FNC output? Several reboots loop.
There is no crash dumps, right?

**Comment by carterw** [comment]
There's no crash dump, it simply reboots over and over. I'll paste in the FNC output later today.

**Comment by alashkin** [comment]
btw, you can try to reflash with `--esp8266-flash-size =4M`

**Comment by carterw** [comment]
Will do.

**Comment by alashkin** [comment]
It is FNC command line options

Run FNC --help (if you don't use Windows)

Also, you can go to Settings -> Advanced settings -> Check "esp8266-flash-size" and put 4M in this field.

**Comment by carterw** [comment]
Flashing with the 4M option eliminated the problem, thanks. Device joined my wifi network after Wifi.setup() and not rebooting. Might want to include this tip in the documentation.

**Comment by alashkin** [comment]
Good to hear that it helped.
I put this tip into FAQ
https://github.com/cesanta/smart.js/blob/master/docs/faq/intro.md#q-i-flashed-esp-module-with-smartjs-it-is-successfully-booted-and-joined-wifi-but-after-reset-the-device-reboots-over-and-over
