### ISSUE TITLE
Websocket removed from API?

### ISSUE THREAD

**Issue by carterw** [cesanta/smart.js#119]
In latest firmware as of today;

smartjs 26732/604$ var ws = new WebSocket('ws://echo.websocket.org');
Exec error: {"message":"options must be an object"}

**Comment by mmikulicic** [comment]
it looks like a bug; there is a second optional parameter and we likely check its presence while we shouldn't.

**Comment by mmikulicic** [comment]
fixed in 78840c44c84dc1e0a7e9e15d20a7521b70624dee
