### ISSUE TITLE
GPIO.setmode is not a function?

### ISSUE THREAD

**Issue by carterw** [cesanta/smart.js#120]
... with freshly built FW;

smartjs 32220/596$ GPIO.setmode(0, 0, 0);
Exec error: {"message":"GPIO.setmode is not a function"}

**Comment by mmikulicic** [comment]
the examples in the doc are out of sync (fixing), the method name is `setMode`

The GPIO API doc for the latest git HEAD is: 

https://docs.cesanta.com/smartjs/dev/#/javascript-api/gpio/
