### ISSUE TITLE
File.list returns same results 

### ISSUE THREAD

**Issue by goliatone** [cesanta/smart.js#13]
`File.list` returns always the same list:

```js
File.list('/var')
```
>"gpio.js","I2C.js","init.js","MC24FC.js","MC24FC_test.js","MCP9808.js","MCP9808_test.js","MPL115A1.js","smart.js","sys.json","user.json"]

```js
File.list('/etc/')
```

>"gpio.js","I2C.js","init.js","MC24FC.js","MC24FC_test.js","MCP9808.js","MCP9808_test.js","MPL115A1.js","smart.js","sys.json","user.json"]

**Comment by cpq** [comment]
Is it on ESP8266 ?
SPIFFS is a flat file system, and doesn't support directories. That might be the reason.
Please reopen if that's not on SPIFFS.

**Comment by goliatone** [comment]
@cpq Look at the quick start guide on the repo's README.

>6. Type some JavaScript expression to the console and press enter. Smart.js evaluates the expression and prints evaluation result: 

![preview](https://camo.githubusercontent.com/6cf16d919f0d5c51f08f500155bc5855f706a654/68747470733a2f2f636573616e74612e636f6d2f696d616765732f736d6172746a735f717569636b5f73746172745f67756964652f6663332e706e67)

**Comment by goliatone** [comment]
@cpq Also, why would you close this issue before getting a response?

**Comment by cpq** [comment]
@goliatone the issue is resolved: SPIFFS is flat.
Please reopen if you think it's not resolved.
