### ISSUE TITLE
How to compile flashnchips for Linux

### ISSUE THREAD

**Issue by maxogden** [cesanta/smart.js#24]
I am trying to use Linux to flash an esp8266 chip with smart.js. I don't see any mention of how to compile flashnchips. In [this post](https://blog.cesanta.com/esp8266-and-iot-smartjs-starter-guide) it says "Linux users can build the binary themselves." but I can't figure out how to compile the code here to run flashnchips on Linux https://github.com/cesanta/smart.js/tree/master/flashnchips

**Comment by mmikulicic** [comment]
You need Qt 5. Install your distributions Qt 5 development libraries or see http://doc.qt.io/qt-5/linux.html

Then:

```
$ qmake
$ make
```

I'll update the README
