### ISSUE TITLE
flashnchips: no errors when serial connection fails

### ISSUE THREAD

**Issue by fedy2** [cesanta/smart.js#26]
Erroneously I've opened two instances of Flash'n'Chips. When I try to flash the device on the second instance pressing the "Flash firmware" button I don't get any feedback. 
In the log I can see the "DEBUG: connectSerial: INTERNAL: Failed to open".
An error message in the UI would be useful.

**Comment by alashkin** [comment]
Current version of FNC shows dialog box with error in this situation.
