### ISSUE TITLE
Build instruction for posix platform on i386 and amd64 architectures

### ISSUE THREAD

**Issue by fedy2** [cesanta/smart.js#34]
Would be nice to have build instruction or better a script file for the building of smart.js for the posix platform under i386 and amd64 architecture.

**Comment by mmikulicic** [comment]
`make` should just work. The reason it doesn't is the same as #33.
If `make` would just work out of the box, would you feel it still needs more documentation?

**Comment by fedy2** [comment]
I've tried `make` but I get this:
```
fedy2@guendalinaXII ~/esp/smart.js/platforms/posix $ make
Makefile:31: ../../../v7/scripts/platform.mk: No such file or directory
make: *** No rule to make target `../../../v7/scripts/platform.mk'.  Stop.
```

**Comment by mmikulicic** [comment]
please pull and retry

**Comment by fedy2** [comment]
Perfect. Is working now.

**Comment by mmikulicic** [comment]
Thanks for reporting!

**Comment by DongDongig** [comment]
I'm also trying to build smart.js for RPI2....
but i cannot figure out how to build...

Could you guide me to build specifically?

I did install "docker" and execute the "armbuild.sh" but I could see

root@ubuntu:/home/ubuntu/smart.js-beta2/smartjs/platforms/posix# ./makearm.sh   GEN build/build_info.c
Traceback (most recent call last):
  File "../../../common/tools/fw_meta.py", line 192, in <module>
    cmd_gen_build_info(args)
  File "../../../common/tools/fw_meta.py", line 66, in cmd_gen_build_info
    repo = get_git_repo(os.getcwd())
  File "../../../common/tools/fw_meta.py", line 29, in get_git_repo
    raise RuntimeError("%s doesn't look like a Git repo" % path)
RuntimeError: /cesanta/smartjs/platforms/posix doesn't look like a Git repo
make: *** [build/build_info.c] Error 1



And When I put just 
$make
root@ubuntu:/home/ubuntu/smart.js-beta2/smartjs/platforms/posix# make
  CC lnx_gpio.c -> build/lnx_gpio.o
  CC lnx_i2c.c -> build/lnx_i2c.o
  CC lnx_spi.c -> build/lnx_spi.o
  CC main.c -> build/main.o
  CC posix_hal.c -> build/posix_hal.o
In file included from posix_hal.c:33:0:
../../../mongoose/mongoose.h:707:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
make: *** [build/posix_hal.o] Error 1

I need to run smart.js on RPI2 or other arm board (32bit)
plz let me know how to do that...
thx in advance!!
