### ISSUE TITLE
Offline icon still visible when no device selected

### ISSUE THREAD

**Issue by fedy2** [cesanta/smart.js#36]
- open the IDE tab https://dashboard.cesanta.com/#/ide
- Selected an offline device
- change to the devices list tab https://dashboard.cesanta.com/#/devices
- return to the IDE tab, there is no device selected but offline icon visible

The issue don't seems appear for other tabs.

**Comment by alashkin** [comment]
cloud.cesanta.com was redesigned, seems this issue is outdated.
I'm closing it, but feel free to reopen it.
