### ISSUE TITLE
Can't connect to ESP webserver

### ISSUE THREAD

**Issue by fedy2** [cesanta/smart.js#43]
The ESP documentation, https://github.com/cesanta/smart.js/tree/master/platforms/esp8266#web-ui,  states that *Smart.js has a built-in web server* that can be access to this address:
http://YOUR_ESP8266_IP_ADDRESS/

When I try to access the address I get a connection refused error.

**Comment by mmikulicic** [comment]
yeah, we struggle keeping the doc up to data.

The http server has been moved to `examples/http_eval/`
We're in progress of rewriting that http server with Mongoose, now that we finally can use the ESP RTOS SDK (and hence BSD socket API)

**Comment by mmikulicic** [comment]
doc fixed, stay tuned
