### ISSUE TITLE
Wifi API improvements

### ISSUE THREAD

**Issue by fedy2** [cesanta/smart.js#44]
Would be useful to have:
- a disconnect function
- a turn off function

**Comment by santiago** [comment]
what about the MAC address

**Comment by mmikulicic** [comment]
@santiago: the mac address is available in the `Sys.ro_vars.mac_address` constant.

**Comment by mmikulicic** [comment]
`Wifi.disconnect()` is implemented. Connect-at-boot setting is controlled by `Sys.wifi.sta.enable` conf var (see configuration UI server at http://192.168.4.1).

@alashkin: my understanding is that when the wifi not actively used the actual wifi circuitry is off; i.e. after Wifi.disconnect() (or after booting when the `wifi.sta.enable` conf is false) the wifi is off and not drawing power. Is that correct ?

**Comment by alashkin** [comment]
@mmikulicic 
`Wifi.disconect` doesn't change configuration, i.e. it works until reboot.
so,
```
wifi.sta.enable=false
wifi.ap.enable=false
Sys.conf.save();
```
is required to permanently turn off Wifi
