### ISSUE TITLE
GPIO API function names inconsistency

### ISSUE THREAD

**Issue by fedy2** [cesanta/smart.js#48]
The `setmode` and `setisr` function names do not follow the camel case convention.

**Comment by realzeus** [comment]
+1

**Comment by alashkin** [comment]
Fixed in https://github.com/cesanta/smart.js/commit/8aec11ff88bde0b0ab2b57759e7ed43fb577743f, see docs here: https://github.com/cesanta/smart.js/blob/master/docs/javascript-api/gpio.md
