### ISSUE TITLE
Does the Button Helper have debouncing logic built in?

### ISSUE THREAD

**Issue by cottsak** [cesanta/smart.js#52]
https://github.com/cesanta/smart.js/blob/master/platforms/esp8266/fs/gpio.js

**Comment by alashkin** [comment]
File was moved to https://github.com/cesanta/smart.js/blob/master/smartjs/src/js/gpio.js
and yes, now it has debouncing logic 
See https://docs.cesanta.com/smartjs/latest/#/javascript-api/gpio/ for details
