### ISSUE TITLE
ESP8266 Coredump stopped by watchdog

### ISSUE THREAD

**Issue by vortex314** [cesanta/smart.js#55]
I'm trying to use the coredump feature on an ESP8266. The Base64 characters are written to UART, however after a few seconds the watchdog seems to kick in and resets the MCU. I get "cause ::4" reset , indicating watchdog reset. Any way to prevent this reset ? 
Really hoping to use this extremely interesting feature for debugging some other issues.

**Comment by alashkin** [comment]
Should be fixed in current version
