### ISSUE TITLE
how to compile with Regex support (ESP8266)

### ISSUE THREAD

**Issue by danyocom** [cesanta/smart.js#57]
Does the ESP8266 build of smart.js support regex? I compiled my own smart.js, and I have the following defined
```
V7_ENABLE__RegExp 1 
```

however, whenever I try to create a regular expression I get the following message

```
Exec error:{"message":"Regexp support is disabled"}
```

**Comment by mmikulicic** [comment]
closed because it works?

**Comment by danyocom** [comment]
Yes, It turns out I did not add the `V7_ENABLE__RegExp` define properly the first time I tried a build with Regex support. It was a case of PEBKAC (Problem Exists Between Keyboard and Chair)
