### ISSUE TITLE
Support for firmware larger than 512k on ESP8266?

### ISSUE THREAD

**Issue by danyocom** [cesanta/smart.js#58]
Is it possible to support a larger firmware size on the ESP8266? I keep running into the following issue when trying to add custom features to the firmware:

`ld: build/smartjs.out section '.irom0.text' will not fit in region 'irom0_0_seg'`

I have a 4MB flash on my ESP8266 and I believe the ESP8266 can access 1MB of Flash at a time, is it possible to have a 1024k firmware size? What files/parameters do I need to change?

**Comment by mmikulicic** [comment]
sure, but you have to manually increase the limit in the linker script in:

```
smartjs/platforms/esp8266/user/eagle.app.30000.v6.ld
```

you also have to tweak the FS location (`FW_FS_ADDR` param in `smartjs/platforms/esp8266`)

Feel free to contribute a better tooling to make this easier.
