### ISSUE TITLE
Http.get unusable for urls containing an IP Address

### ISSUE THREAD

**Issue by danyocom** [cesanta/smart.js#60]
I am unable to use the Http.get API in the Alpha 2.1 to access servers using their ip address. Servers that rely on DNS to resolve the hostname into an IP address work fine, but when trying to access a server via IP address directly (http://192.168.1.xxx) the callback is never called.

Using the Http.request API that is in the latest codebase, I am able to access urls that contain IP addresses, however, the Http.request function eats memory and I can only make 10 or so calls before I am out of memory

**Comment by mmikulicic** [comment]
yeah alpha 2.1 has some toy http client. Current master has full featured nodejs' style `Http.request` that uses mongoose under the hood and supports the full uri syntax.
