### ISSUE TITLE
Docker required but not mentioned in README

### ISSUE THREAD

**Issue by eallik** [cesanta/smart.js#69]
https://github.com/cesanta/smart.js/tree/master/platforms/esp8266

does not mention that `docker` is required for installation.

also it might be useful to include a link to how docker can be set up so that `make` inside `esp8266` would work?

**Comment by mmikulicic** [comment]
The readme actually mentions it:

‘‘‘
For those who want to build/customize the firmware, make sure you have docker installed and running
‘‘‘

A link to some install doc at the docker website wouldn't hurt though

**Comment by eallik** [comment]
Apologies, missed it.
