### ISSUE TITLE
On boot, please log version identity.

### ISSUE THREAD

**Issue by nkolban** [cesanta/smart.js#75]
When I reboot an ESP8266 running Smart.js, I'd like to see the version of the Smart.js logged to the console so that I can validate what version is being used.

**Comment by mmikulicic** [comment]
yeah, it makes sense. I'll add it to the default startup script.

FYI: you can print the current version by just typing `version` at the prompt (it's a global variable)
or to your custom user.js startup script.

**Comment by alashkin** [comment]
Current version prints on boot:
`This is Smart.JS 20160412064031 (esp8266)`
