### ISSUE TITLE
WebSocket client not working

### ISSUE THREAD

**Issue by snsekar** [cesanta/smart.js#90]
Hi,
Today i flashed windows build from here https://github.com/cesanta/smart.js on my esp8266-01. I am trying to run WebSocket example given here https://www.cesanta.com/developer/smartjs#_websocket

But i am getting Exec error: {"message":"error creating the connection"}
![error1](https://cloud.githubusercontent.com/assets/5658203/12271390/c197a4a4-b980-11e5-98bc-8d60e75aab97.PNG)

However i am able to connect to Wifi successfuly and Http.request is working fine.

**Comment by mmikulicic** [comment]
@alashkin reproduced with HEAD

**Comment by mmikulicic** [comment]
@alashkin sj_mongoose_websocket just passes the raw arg to mongoose low level tcp connect.
It should use http connect

**Comment by snsekar** [comment]
Thanks for looking into this issue. If WebSocket client works fine, this will be killer feature for our project.

**Comment by mmikulicic** [comment]
Hi @snsekar,

The latest master branch has working websocket support. Could you please try it out?

**Comment by snsekar** [comment]
Wow great...i am out of office now. I wont be able to check couple of days. I will update here when i check

**Comment by marsteini** [comment]
Hi, I'm experiencing the same problem. Is there a binary build of the current branch?

**Comment by mmikulicic** [comment]
The latest binary build is available at https://github.com/cesanta/smart.js under the `Current development Smart.js firmware builds` bullet.

This issue has been fixed. Feel free to reopen if you have any problems.

**Comment by snsekar** [comment]
Thanks for fixing this issue. I will check

**Comment by snsekar** [comment]
I checked the build mentioned by @mmikulicic . WebSocket Client working now.
