### ISSUE TITLE
Flash'n'Chips 0.8 Error "Image will not fit in flash"

### ISSUE THREAD

**Issue by olterion** [cesanta/smart.js#94]
I have a ESP01 and I want to flash it with the Smart.js firmware "smartjs-20160128174140" and use the Flash'n'Chips 0.8 flasher.
I have the GPIO0 conntected to ground.
But everytime I want to start the flash process, there is a error "Image 487840 @ 0x11000 will not fit in flash (size 524288)"
Are there different ESP01 at the market?
Or is that a error in the flash program?

**Comment by mmikulicic** [comment]
Hi,

Stock Smartjs beta2 requires devices with bigger flashes such as esp12.  If you want to flash it on esp01 you need to build a fw with a smaller flash filesystem. In order to do so you have to change the FS size parameter in the eap8266 platform makefile.
